### ISSUE TITLE
Problem of sharing pictures via share extension

### ISSUE THREAD

**Issue by AndreaVEH** [wireapp/wire-ios#1320]
There is a problem when sharing pictures via share extension. If I just share a picture without inputting any additional text, the panel always displays "Preparing".

![img_0051](https://user-images.githubusercontent.com/7317368/31211090-2bc7f00a-a95c-11e7-8e03-319a378b69fe.PNG)

And if I share a picture and also input some additional text, only the text will appear in the conversation, the picture seems to be discarded.

But if I copy the picture and paste it in the input field of the conversation, I can successfully send it.

Device: iPhone SE
iOS version: 11.0.2
Wire version: 2.43 (2895)

**Comment by mikeger** [comment]
Hey @AndreaVEH ! Thanks for the report, I believe we fixed this one on `develop` already, let's check with the next release.

**Comment by nicorsm** [comment]
I can confirm that, messages with attached images are sent correctly with the last version from `develop`. Thank you for your feedback @AndreaVEH!

**Comment by AndreaVEH** [comment]
Hello, @nicorsm & @mikeger . I'm using Version 3.0(2902) on iOS 11.0.3 now. When I share the picture in Twitter app via share extension, the same problem still occurs. But if I save the picture, then share it in Photos via share extension, it works.

**Comment by AndreaVEH** [comment]
- I choose 'Open in Safari' instead of share extension of Wire with the picture this time. Safari appears and only the picture is shown in it. I respectively share the webpage to iMessage and Wire. iMessage app can know I'm sharing a picture and only the picture shown in the text field. Wire app prompts the share panel with the url of the picture, additional information about the picture and a thumb of the picture. If I just choose the conversation and send it, only the text will appear in the conversation. But if I clear all the text and send it, the panel will always display 'Preparing'.

- If I share a picture within a iMessage conversation via share extension to Wire, it works with no problem.

- Directly copying and pasting the picture into the input field then sending it still works.

I hope those above can provide you with some additional information.

**Comment by AndreaVEH** [comment]
Hello, @mikeger and @nicorsm . The same problem still seems to exist in the Version 3.1(2911).

**Comment by nicorsm** [comment]
Hello @AndreaVEH, thank you for your feedback! We'll take a look at this issue on the next releases.

**Comment by AndreaVEH** [comment]
Hello @nicorsm and @mikeger , the problem seems to be fixed in the Version 3.2(2921). Thank you for your work! 👍
