### ISSUE TITLE
Photo library does not load previous images

### ISSUE THREAD

**Issue by EgbertW** [wireapp/wire-ios#1766]
## Checklist (please check before submitting)

* [x] I checked the existing issues, and the issue was not reported before.

## The problem

When viewing an image, you can swipe back and forth to see previous or later images. However, once I get two or three images back, I just get a blank screen. I tried waiting several minutes but the photo just doesn't show up.

## Environment

I'm running Wire 3.7 (2969) on an iPhone 5S, iOS 10.3.3. I have contacts with an iPhone 6 and an iPhone 6s that report similar issues.

I'm always experiencing this issue, both on 4G and Wi-Fi.

## Details

Steps to reproduce: open a (large) conversation with several images. Tap top open one message and swipe back to see earlier images.

When scrolling back through the conversation history, the images do seem to pop up correctly where they belong, although this also sometimes takes over 10 seconds.

**Comment by mikeger** [comment]
Hey @EgbertW ! Thanks for reporting the issue, we'll take a look into it.

**Comment by mikeger** [comment]
Hey @EgbertW ! The issue must be fixed in the current (3.8) release. Please give it a try!

**Comment by EgbertW** [comment]
Thanks @mikeger - I just tried. A slight improvement: I don't get a fully black loading screen now, I get a loading spinner in the center of the screen. Unfortunately, the image still doesn't load and the spinner just keeps on spinning.

**Comment by jswedenburg** [comment]
Hi. Is this still an issue? I'll give it a go.
