### ISSUE TITLE
Severe repeating issues with media upload/download

### ISSUE THREAD

**Issue by anatoli26** [wireapp/wire-ios#792]
This is a cross-platform issue, so posting it here too. The initial report is here: https://github.com/wireapp/wire-desktop/issues/472.

Second try: uploading 3 photos from iPhone's Photo gallery > Select (3 photos) > Share > Wire > Select the conversation and a description.

Repeating the same for a video. It hangs for some 15 seconds in the Photo gallery, I switch to Wire.

There I see the 3 photos in sending state + the video. I note that the description had an error, so I force-touch press it > Edit > Save.

The transfer of the media files looks like hanged, even the description update is not passing. After some minutes the description message changes state to failed, I press resend, the app crashes.

I reopen the app, one photo makes it to the server, the rest is still hanged. I cancel the upload of the video, the photos are almost instantly uploaded. I press to retry the video upload, it also quickly uploads.

I haven't seen the code yet, but I imagine it is one file at a time and is synchronous (vs asynchronous). Also, I suppose it has infinite or considerably long timeout. And it definitely reserves an upload slot at the servers.

I would recommend to make:
- the upload process asynchronous,
- each file to be uploaded independently,
- with short timeout (e.g. 10 seconds on no progress, then automatically retry for 5 times incrementing the timeout by 10s each try),
- no upload slot reservations on the server: FIFO,
- and especially not to notify the peer about incomplete uploads (this just makes everything extremely complex, error-prone and significantly confuses the users when there are issues with the connection on the uploader side). Once the file is completely uploaded, it gets some ID and only then its existence is notified to the peer(s)/other devices.

### Versions
- iPhone 6S
- iOS 10.2.1
- Wire 2.30.2780

**Comment by jenskasemets** [comment]
@anatoli26  please update to latest available version, this issue should have been fixed in 2.31

**Comment by anatoli26** [comment]
I've tried multiple times this issue with v2.33 and everything looks working fine, so for me it's fixed. What's not yet fixed, is that the peer gets a pre-visualization for any type of attachment (voice, photo, video) before the attachment uploads fully to the server.

This is extremely confusing on slow/intermittent connections. Users say that attachments on Wire work extremely slow, not realizing actually that the slow is the connection of their peers. Also if the attachment doesn't upload fully to the server at all, it's left in some unclear state.

Why not to notify the peer of new attachments only when they fully uploaded to the server? This will _drastically_ improve the UX and reduce errors/strange behavior.
